### ISSUE TITLE
ENABLE ORGANIZATION

### ISSUE THREAD

**Issue by cllouud** [cllouud/test-ascend-ci-permission#1]
Welcome to use this template to submit an issue to add your organization to the NPU Runners. Please follow the instructions below to fill in the relevant information so that we can process your request more efficiently.

```yaml
org-name:  erwrwr
github-app: 
  instalation-id:  wrwr 
runner-group: 
  group-name:  qttewtrer
runner-set: 
  npu-counts: 1, 2
```

| Field | Description | Example | Required |
|------|------|------|-----|
| `org-name` | Full name of the organization | `awesome-ai-org` | ✅ |
| `github-app.installation-id` | Installation ID after installing ascend-runner-mgmt | `11111111` | ✅ |
| `runner-group.group-name` | The group name of the configured runner group | `ascend-ci` | ✅ |
| `runner-set.npu-counts` | The number array of NPU chip | `1,2` | ✅ |
